Пока на методе makeStep() стоит заглушка, тестов ещё тоже нет.
Dervun/Homeworks pull request #28
Opened 2016-09-20 20:25 UTC by Dervun

2016-09-28 13:49 UTC, jzuken requested changes

2016-09-28 13:49 UTC, jzuken commented on 3/Homework 2/task_2_1/localareanetwork.cpp
> +        if (computers[i]->isInfected())
ну вот не стыдно так писать?

2016-09-28 13:49 UTC, jzuken commented on 3/Homework 2/task_2_1/localareanetwork.cpp
> +        if (computers[i]->isInfected())
и, кстати, почему бы просто не хранить заражённые компьютеры в поле класса?

2016-09-28 13:49 UTC, jzuken commented on 3/Homework 2/task_2_1/localareanetwork.cpp
> +LocalAreaNetwork::LocalAreaNetwork(FILE *informationFile)
какой-то слишком большой конструктор, хочется разбить его на несколько методов

2016-09-28 13:49 UTC, jzuken commented on 3/Homework 2/task_2_1/localareanetwork.h
> +class LocalAreaNetwork
тест на локалку тоже хочется

2016-10-05 13:58 UTC, jzuken requested changes

2016-10-05 13:58 UTC, jzuken commented on 3/Homework 2/task_2_1/computer.cpp
> +    if (currentProbability < probabitityOfInfection)
а если он уже был заражён до этого?

2016-10-05 13:58 UTC, jzuken commented on 3/Homework 2/task_2_1/networkfortest.h
> +class NetworkForTest : public LocalAreaNetwork
хочется комментариев ко всем классам

2016-10-05 15:57 UTC, Dervun commented on 3/Homework 2/task_2_1/computer.cpp
> +    if (currentProbability < probabitityOfInfection)
Он как был заражённым, так и останется.

2016-10-05 16:50 UTC, Dervun commented on 3/Homework 2/task_2_1/computer.cpp
> +    if (currentProbability < probabitityOfInfection)
Стоп, так у меня в любом случае эта функция вызывается только после проверки, что компьютер не заражён.
if (!infected[j])
    tryToInfect(j);

2016-10-07 08:37 UTC, merged